export enum CommandAction {
  ACTIVATE_SHOW_ASSOCIATIONS, TOGGLE_SHOW_ASSOCIATIONS,
  GROUP_CELLS, UNGROUP_CELLS, ACTIVATE_CELL_GROUPING, ACTIVATE_CELL_UNGROUPING,
  SHOW_MATRICES,
  TURN_CELL_ON, TURN_CELL_OFF, ACTIVATE_TURN_OFF_CELL, ACTIVATE_TURN_ON_CELL,
  EXPORT_GRAPH_AS_PNG,
  EDIT_Dp_DETRACTOR_MATRIX,
  EDIT_Dq_DETRACTOR_MATRIX,
  IMPORT_GRAPH_MODEL,
  SAVE_GRAPH_MODEL,
  COMPARE_GRAPH_MODELS
}

export interface Command {
  action: CommandAction;
  payload: any;
}